package com.learn.LearnSpringBoot.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data   //for getting getter setter from lombok app
@AllArgsConstructor //parameterized constructor will be generated by lombok
@NoArgsConstructor  //non-parameterized constructor 
public class Student {

	private int id;
	private String name;
	private int marks;
	
	
	
	
	
}
